name: Deployment
on:
  push:
    branches:
      - main
      - dev
env:
  MONGODB_DB_NAME: sample_mflix
jobs:
  test: # change to mysql
    environment: testinng
    env:
      MONGODB_CLUSTER_ADDRESS: cluster0.hz3rz.mongodb.net
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}"
  Deploy:
    needs: test
    runs-on: ubuntu-latest
    steps: 
      - name: output contant
        run: ls 
      - name: Deploy
        run: echo "Deployed"

